In [1]:
a=input()

KeyboardInterrupt: Interrupted by user

In [ ]:
type(a)

In [ ]:
a=float(input())

In [ ]:
type(a)

In [ ]:
a=int(input())

In [ ]:
type(a)

In [ ]:
a=123
b=-123
c=0

In [ ]:
type(a)

In [ ]:
a=1.2
b=-2.1

In [ ]:
type(b)

In [ ]:
a=1.24e-2

In [ ]:
a

In [ ]:
b=1.24E2

In [ ]:
b

In [ ]:
10<15

In [ ]:
10<=5

In [ ]:
10>61

In [ ]:
print(bool(1))

In [ ]:
print(bool(0))

In [ ]:
print(())

In [ ]:
print(bool(""))

In [ ]:
print(bool("안녕"))

In [ ]:
1 == 1

In [ ]:
1 == 0

In [ ]:
1 != 0

In [ ]:
not 1 == 1

In [ ]:
1 == 1 and 1 == 2

In [ ]:
1 == 1 or 1 == 2

In [ ]:
'Life is too short, You need Python'

In [ ]:
"a"

In [ ]:
"123"

In [ ]:
food = "Python's favorite food is perl"

In [ ]:
type(food)

In [ ]:
python='python'

a='python'
b=2

a*b

In [ ]:
print('='*50)
print("My Program")
print('='*50)

In [ ]:
A = [1,2,3,4,5]
type(A)

In [ ]:
B = list[1,2,3,4,5]
type(B)

In [ ]:
a="독고영재, 50"
b="김철수, 30"
c = ["독고영재, 50", "김철수, 30"]

c

In [ ]:
a=[1,2,3]
b=[5,6,7]
c=a+b
c

In [ ]:
a=[1,2,3,"a"]
b=[5,6,7,"b"]
c=a+b
c

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
b=np.array([5,6,7])
c=a+b
type(c)

In [ ]:
a=np.array([1,2,3,'a'])
b=np.array([5,6,7,'b'])
c=a+b
c

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=a+b
type(c)
c.shape

In [ ]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다."
A[0:5]

In [ ]:
A[21:23]

In [ ]:
A[-6:-4]

In [ ]:
print("안녕하세요\n반갑습니다.")

In [ ]:
A = "당신의 영어 성적은 {}점입니다. 그리고 수학 성적은 {}점입니다."
A.format(100,86)

In [ ]:
print(("{:.2f}, {:.3f}").format(3.1415,3.1415))

In [ ]:
url = "https://www.youtube.com/"
str = url.replace("youtube","naver")

print(str)

In [ ]:
A = ["독고영재, 50", "김철수, 30"]
A[0][0:4]

In [ ]:
a = "독고영재, 50" 
b = "김철수, 30"
a[:a.index(",")]
b[:b.index(",")]

In [ ]:
a = ["독고영재, 50", "김철수, 30"]
b = ["김철수, 20", "김영희, 25"]

a[0][:a[0].index(",")]

In [ ]:
b[1][:b[1].index(",")]

In [ ]:
a = [10,20,30,[1,2,3]]
a[3]
math = [20,30,40,50,60]
English = [50,70,50,60,90]

math_aver = sum(math)/5
print(math_aver)

In [ ]:
a=["hi", 10, "80", "김철수",50,50.6]
a.pop(1)
a

In [ ]:
a=["hi", 10, "80", "김철수",50,50.6]
a.append(1)
a

In [ ]:
a=["hi", 10, "80", "김철수",50,50.6]
a.index(50)
a.pop(4)
a

In [ ]:
a=["hi", 10, "80", "김철수",50,50.6]
a.index("80")
a.pop(2)
a[0]

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a = np.append(a, [4,5])

In [ ]:
a=np.insert(a,2,[7,8])
a

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
a=np.delete(a, [1,3])

In [ ]:
a=a[a<=4]

In [ ]:
a=a[a!=4]
a

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]]) 
merged_array = np.vstack((array1, array2))
print(merged_array)

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]]) 
merged_array = np.hstack((array1, array2))
print(merged_array)

In [ ]:
A = {1: "김철수", 20: "박영희"}

In [ ]:
A.get(3)

In [ ]:
A = {"1-A" : "김철수", "20-B": "박영희"}
A["2-A"] = "영희"
A

In [ ]:
A={
"1-A": [1,2,3,4,5], 
"20-B": ["A","B","C","D","E"]
}

A

In [ ]:
#1
a = [10, 20, 30, [1,2,3]]

In [ ]:
#2
print(a[3])

In [ ]:
#3
수학점수 = [20, 30, 40, 50, 60]
영어점수 = [50, 70, 50, 60, 90]

In [ ]:
#4
url = "https://www.youtube.com/"
url2 = url.replace("youtube", "naver")
print(url2)

In [ ]:
#5
수학점수_평균 = sum(수학점수)/5
영어점수_평균 = sum(영어점수)/5

print("수학점수 평균 : ", 수학점수_평균)
print("영어점수 평균 : ", 영어점수_평균)

In [ ]:
#6
a = np.array([1,2,100,4,5,900])
b = np.delete(a, [2,-1])
print(b)

In [ ]:
#7
A = {"수학점수" : [20,30,40,50,60],
     "영어점수" : [50,70,50,60,90]}

In [ ]:
#8
print((A["수학점수"][0]+A["영어점수"][2]))

In [ ]:
import pandas as pd

In [ ]:
data = { 
        'Name' : ['Alice','Bob','Charlie'],
        'Age' : [25,30,35],
        'City' : ['New York', 'Paris', 'London']
}

In [ ]:
print(data)

In [ ]:
df = pd.DataFrame(data)

In [ ]:
print(df)

In [112]:
import numpy as np

In [ ]:
data = np.array([
    [1, 'Alice', 30],
    [2, 'Bob', 25],
    [3, 'Charlie', 35]
])

In [ ]:
print(data)

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df = pd.DataFrame(data, columns=['ID','Name','Age'])

In [ ]:
df_h=pd.read_csv("C:/Users/USER/Desktop/data/국영수.csv", header=0, encoding='cp949')

In [ ]:
df_h

In [ ]:
df=pd.read_csv("C:/Users/USER/Desktop/data/국영수.csv", header=0, encoding='cp949')

In [ ]:
df

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.dtypes

In [ ]:
df.describe()

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.isnull().sum()

In [ ]:
df['체육'].value_counts()

In [ ]:
df['체육'].unique()

In [ ]:
df['체육'].nunique()

In [ ]:
df["합계"] = df["국어"]+df["영어"]

In [ ]:
df

In [ ]:
columns = ['국어','영어','수학']

In [ ]:
selected_columns = df[columns]
selected_columns

In [ ]:
df.loc[:,"수학"]

In [ ]:
columns = ['국어','영어','수학']
selected_columns = df.loc[:,columns]

In [ ]:
df= df.drop(["체육"],axis=1)

In [ ]:
df

In [ ]:
data = {
        'A' : [1,2,3,4],
        'B' : [4.1,3.5,2.1,5.7],
        'C' : ['one','two','three','four']
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df['A'] = df['A'].astype(float)
df['B'] = df['B'].astype(int)
df['C'] = df['C'].astype('category')

In [ ]:
print(df)

In [ ]:
df.dtypes

In [ ]:
df['A'].dtype

In [ ]:
df['B'].dtype

In [ ]:
df['C'].dtype

In [ ]:
df['A']=df['A'].astype('str')

In [ ]:
df['A'].dtype

In [ ]:
#숫자를 문자열로 바꿀 순 있지만 문자열을 다시 숫자로 바꾸면 error 발생

In [ ]:
df = df.rename(columns={"A":"국어",
                        "B":"영어",
                        "C":"번호"})

In [ ]:
df

In [ ]:
data = {"Numeric1" : [1,np.nan,3,4],
        "Numeric2" : [5,6,np.nan,8.2],
        "Category" : ['dog',np.nan,'cat','dog']}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
A=df.select_dtypes(include=["number"]).columns

In [ ]:
df[A]

In [ ]:
A

In [ ]:
B=df.select_dtypes(include=['object', 'category']).columns

In [ ]:
df[B]

In [ ]:
df[A].fillna(df[A].mean())

In [ ]:
df[A].fillna(df[A].median())

In [ ]:
df[A]= df[A].fillna(df[A].median())

In [ ]:
df1 = pd.DataFrame({
    'a':['a0','a1','a2','a3'],
    'b':['b0','b1','b2','b3'],
    'c':['c0','c1','c2','c3']
})

df2 = pd.DataFrame({
    'a':['a2','a3','a4','a5'],
    'b':['b2','b3','b4','b5'],
    'c':['c2','c3','c4','c5'],
    'd':['d2','d3','d4','d5']
})

In [ ]:
pd.concat([df1,df2],axis=0) #행기준

In [ ]:
pd.concat([df1,df2],axis=1) #열기준

In [ ]:
pd.concat([df[A],df[B]],axis=1)

In [ ]:
df[(df['Numeric2'] >= 6) & (df['Numeric2'] <= 10)]

In [ ]:
df[(df['Numeric2'] >= 6) | (df['Numeric2'] <= 10)]

In [ ]:
-------------------------------------------------------------------------

In [4]:
import pandas as pd
import numpy as np

In [12]:
data = {'Numeric1':[1, np.nan, 3, 4],
        'Numeric2':[5,6,np.nan,8.2],
        'Category':['dog',np.nan,'cat','dog']}

In [13]:
df = pd.DataFrame(data)

In [14]:
df[df['Numeric2']<8]

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN

In [16]:
data = {'나이':[22,35,14,55,42]}

df = pd.DataFrame(data)

def categorize(data):
    if 0<data<=10:
        return "10대"
    elif 10<data<=20:
        return "20대"
    elif 20<data<=30:
        return "30대"
    else:
        return "30대 이상"

In [17]:
df['검사나이'] = df['나이'].apply(categorize)

In [18]:
df

   나이    검사나이
0  22     30대
1  35  30대 이상
2  14     20대
3  55  30대 이상
4  42  30대 이상

In [20]:
data = {'Numeric1':[1, np.nan, 3, 4],
        'Numeric2':[5,6,np.nan,8.2],
        'Category':['dog',np.nan,'cat','dogg']}

df = pd.DataFrame(data)

In [21]:
filter_df = df[df['Category']=='dog']

In [22]:
filter_df

   Numeric1  Numeric2 Category
0       1.0       5.0      dog

In [23]:
filter_df_contains = df[df['Category'].str.contains('do',na=False)]

In [24]:
filter_df_contains

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
3       4.0       8.2     dogg

In [25]:
df = pd.DataFrame({
'variable': ['value1-value2-value3', 'value4-value5', 'value6']
})

In [26]:
split_df = df['variable'].str.split('-',expand=True)

In [27]:
split_df.columns = ['var1','var2','var3']

In [28]:
split_df

     var1    var2    var3
0  value1  value2  value3
1  value4  value5    None
2  value6    None    None

In [43]:
df = split_df

In [41]:
df['variable'] = df['variable'].str[0:5]
df['variable']

0    value
1    value
2    value
Name: variable, dtype: object

In [40]:
df['variable'] = df['variable'].str[0:5] + df['variable'].str[6:12]
df['variable']

0    value
1    value
2    value
Name: variable, dtype: object

In [44]:
df['var1'] = df['var1'].astype(str)
df['var2'] = df['var2'].astype(str)
df['var3'] = df['var3'].astype(str)

In [45]:
df['combined'] = df['var1'] + '-' + df['var2'] + '-' + df['var3']

In [46]:
df

     var1    var2    var3              combined
0  value1  value2  value3  value1-value2-value3
1  value4  value5    None    value4-value5-None
2  value6    None    None      value6-None-None

In [47]:
text = "apple, "
result = text.rstrip(", ")
print(result)
text = "banana, , "
result = text.rstrip(", ")
print(result)
text = ",orange, pear"
result = text.lstrip(", ")
print(result)

apple
banana
orange, pear

In [61]:
df = pd.DataFrame({
"문항1" : ['1','2'," ",'2'],
"문항2" : [" ",'2','3'," "]
})

df["문항"] = df["문항1"].fillna(" ") + "," + df["문항2"].fillna(" ")
#df["문항"] = df["문항1"].str.rstrip(",")
#df["문항"] = df["문항1"].str.lstrip(",")
#df = df.drop(columns=["문항1", "문항2"])
df

  문항1 문항2   문항
0   1      1,
1   2   2  2,2
2       3   ,3
3   2      2,

In [62]:
df["문항"] = df["문항1"].fillna(" ") + "," + df["문항2"].fillna(" ")
df

  문항1 문항2   문항
0   1      1,
1   2   2  2,2
2       3   ,3
3   2      2,

In [63]:
df["문항"] = df["문항1"].str.rstrip(",")
df

  문항1 문항2 문항
0   1      1
1   2   2  2
2       3
3   2      2

In [64]:
df["문항"] = df["문항1"].str.lstrip(",")
df

  문항1 문항2 문항
0   1      1
1   2   2  2
2       3
3   2      2

In [65]:
df = df.drop(columns=["문항1", "문항2"])
df

  문항
0  1
1  2
2
3  2

In [74]:
df = pd.DataFrame({
"문항1" : ['1','2'," ",'2'],
"문항2" : [" ",'2','3'," "],
"문항3" : [" ",'1','2'," "],
})

In [75]:
cols = ["문항1", "문항2", "문항3"]
df[cols] = df[cols].replace(r'^\s*$','무응답',regex=True)

In [77]:
df['문항'] = df['문항1'].fillna("")+","+ df['문항2'].fillna("") + "," + df['문항3'].fillna("")

In [78]:
df

   문항1  문항2  문항3         문항
0    1  무응답  무응답  1,무응답,무응답
1    2    2    1      2,2,1
2  무응답    3    2    무응답,3,2
3    2  무응답  무응답  2,무응답,무응답

In [82]:
df = pd.DataFrame({
'variable': ['value1-value2-value3', "value3-value1-value5", "vvdfvalue165656"]
})

In [81]:
df["new_variable"]=df["variable"].str.replace(r'value1.*', 'value1', regex=True)
print(df["new_variable"])

0           value1
1    value3-value1
2       vvdfvalue1
Name: new_variable, dtype: object

In [84]:
df = pd.DataFrame({
'variable': ['value1-value2-value3', "value3-value1-value5", "vvdfvalue165656"]
})

df["new_variable"]=df["variable"].str.extract(r'(value1)')
print(df["new_variable"])

0    value1
1    value1
2    value1
Name: new_variable, dtype: object

In [85]:
df["new_variable"]=df['variable'].str.extract(r'(value2)')
print(df["new_variable"])

0    value2
1       NaN
2       NaN
Name: new_variable, dtype: object

In [114]:
data = {'date': ['202103151345', '20210315 1345', '0715', '07-15', '20210315','1']}
df = pd.DataFrame(data)

In [115]:
df['date']=pd.to_datetime(df['date'], format='%Y%m%d %H%M', errors='coerce')
df

                 date
0                 NaT
1 2021-03-15 13:45:00
2                 NaT
3                 NaT
4                 NaT
5                 NaT

In [105]:
df['date']=pd.to_datetime(df['date'], format='%H-%M', errors='coerce').dt.time 
df

       date
0       NaT
1       NaT
2       NaT
3  07:15:00
4       NaT
5       NaT

In [116]:
df['date']=pd.to_datetime(df['date'], format='%Y%m%d', errors='coerce')
df

                 date
0                 NaT
1 2021-03-15 13:45:00
2                 NaT
3                 NaT
4                 NaT
5                 NaT

In [134]:
data = {'hour': ['1', '2', '12', '22','11']}
df = pd.DataFrame(data)

In [136]:
pd.to_datetime(df['hour'], format='%H%M',errors='coerce').dt.time

0    10:00:00
1    20:00:00
2    12:00:00
3    22:00:00
4    11:00:00
Name: hour, dtype: object

In [132]:
df['hour'] = df['hour'].str.rjust(4, fillchar='0')

In [135]:
df['hour'] = df['hour'].str.ljust(4, fillchar='0')

In [138]:
df.to_csv('C:/Users/USER/Desktop/data/new_program.csv', index = False, encoding='cp949')

In [144]:
df = pd.read_csv('C:/Users/USER/Desktop/data/program_1.csv', header=0, encoding='cp949')

In [145]:
df

  코드  프로그램1  프로그램2  프로그램3  프로그램4
0  A     57   24.0   85.0   47.0
1  B     56   98.0   65.0    0.0
2  C     62   89.0    NaN   66.0
3  D     54    NaN   94.0   54.0
4  E     54   54.0   47.0   84.0
5  F     23   51.0   71.0    NaN

In [147]:
df.dtypes

코드        object
프로그램1      int64
프로그램2    float64
프로그램3    float64
프로그램4    float64
dtype: object

In [150]:
df_num = df.select_dtypes(include=["number"])
df_obj = df.select_dtypes(include=['object'])
df_num = df_num.fillna(df_num.mean())
df = df_num

In [151]:
df

   프로그램1  프로그램2  프로그램3  프로그램4
0     57   24.0   85.0   47.0
1     56   98.0   65.0    0.0
2     62   89.0   72.4   66.0
3     54   63.2   94.0   54.0
4     54   54.0   47.0   84.0
5     23   51.0   71.0   50.2

In [153]:
df_2 = pd.concat([df_obj, df_num], axis=1)
df_2

  코드  프로그램1  프로그램2  프로그램3  프로그램4
0  A     57   24.0   85.0   47.0
1  B     56   98.0   65.0    0.0
2  C     62   89.0   72.4   66.0
3  D     54   63.2   94.0   54.0
4  E     54   54.0   47.0   84.0
5  F     23   51.0   71.0   50.2

In [154]:
col = ['프로그램1', '프로그램2', '프로그램3', '프로그램4']
df_2['평균'] = df_2[col].mean(axis=1)

In [155]:
df_2

  코드  프로그램1  프로그램2  프로그램3  프로그램4     평균
0  A     57   24.0   85.0   47.0  53.25
1  B     56   98.0   65.0    0.0  54.75
2  C     62   89.0   72.4   66.0  72.35
3  D     54   63.2   94.0   54.0  66.30
4  E     54   54.0   47.0   84.0  59.75
5  F     23   51.0   71.0   50.2  48.80

In [161]:
def score(data):
    if 0<data<=55:
        return "하"
    elif 55<data<=70:
        return "중"
    else:
        return "상"

In [164]:
df_2['평가분류'] = df_2['평균'].apply(score)

In [165]:
df_2

  코드  프로그램1  프로그램2  프로그램3  프로그램4     평균 평가분류
0  A     57   24.0   85.0   47.0  53.25    하
1  B     56   98.0   65.0    0.0  54.75    하
2  C     62   89.0   72.4   66.0  72.35    상
3  D     54   63.2   94.0   54.0  66.30    중
4  E     54   54.0   47.0   84.0  59.75    중
5  F     23   51.0   71.0   50.2  48.80    하

In [171]:
filter_df = df_2[df_2['평가분류']=='상']

In [173]:
filter_df_contains = df_2[df_2['평가분류'].str.contains('상', na=False)]

In [ ]:
filter_df = res_indexing.reset_index(drop=True)